# -*- coding: utf-8 -*-
"""ZomatoData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11LZ6yQIXYx5dXL4wkeUau2i4O55AkImo
"""

# import pandas as pd
# df = pd.read_csv('zomato.csv')
# df.head()

import pandas as pd
import csv
import sys

# Increase the field size limit to the maximum possible value
csv.field_size_limit(sys.maxsize)

df = pd.read_csv('zomato.csv', engine='python', on_bad_lines='skip')

df.head()

df.drop(columns=['url','phone','rest_type','dish_liked','reviews_list','menu_item','listed_in(city)'] , axis=1, inplace = True)

df.info()

df.rename(columns={'approx_cost(for two people)':'two_people_cost','listed_in(type)':'type_of_restaurant','rate':'rating'}, inplace=True)

df.dropna(subset=['location','cuisines','two_people_cost'] , inplace = True)

df.drop_duplicates(inplace=True)

df.info()

df['two_people_cost'] = df['two_people_cost'].str.replace(',', '').astype(int)

df.info()

df['two_people_cost'] = df['two_people_cost']/2
df.rename(columns={'two_people_cost': 'cost_per_person'}, inplace='True')
df.info()

df[['name','online_order','location','cuisines','type_of_restaurant', 'address', 'book_table']]=df[['name','online_order','location','cuisines','type_of_restaurant', 'address', 'book_table']].astype('string')
df.info()

df['rating'].head()

import numpy as np
def handlerate(value):
  if(value == 'NEW' or value=='-' or value== ''):
    return np.nan
  else:
    value = str(value).split('/')
    value = value[0]
    return float(value)
df['rating']  = df['rating'].apply(handlerate)
df['rating'].head()

df.info()

df['rating'].view()

df['rating'] = df['rating'].fillna(0)
df.info()

df.to_csv('zomato_clean_data_5july.csv')